image: python:3.13

lint:
  tags:
    - shared
  script:
    - python -m venv venv
    - source venv/bin/activate
    - make install
    - make lint

test:
  tags:
    - shared
  script:
    - python -m venv venv
    - source venv/bin/activate
    - make install
    - make test
