specfile_path: packaging/shellai.spec
upstream_package_name: shellai
downstream_package_name: shellai
upstream_project_url: https://github.com/rhel-lightspeed/shellai

srpm_build_deps: []

jobs:
  # Build RPMs for each pull request
  - job: copr_build
    trigger: pull_request
    owner: "@rhel-lightspeed"
    project: shellai
    targets:
      - epel-8-x86_64
      - epel-9-x86_64
      - epel-10-x86_64
    actions:
      # do not get the version from a tag (git describe) but from the spec file
      get-current-version:
        - grep -oP '^Version:\s+\K\S+' packaging/shellai.spec

  # Build RPMs for main branch
  - job: copr_build
    trigger: commit
    branch: main
    owner: "@rhel-lightspeed"
    project: shellai
    targets:
      - epel-8-x86_64
      - epel-9-x86_64
      - epel-10-x86_64
    actions:
      # bump spec so we get release starting with 2 and hence all the default branch builds will
      # have higher NVR than all the PR builds
      post-upstream-clone:
        - rpmdev-bumpspec --comment='latest upstream build' ./packaging/shellai.spec
      # do not get the version from a tag (git describe) but from the spec file
      get-current-version:
        - grep -oP '^Version:\s+\K\S+' packaging/shellai.spec
