specfile_path: packaging/command-line-assistant.spec
upstream_package_name: command-line-assistant
downstream_package_name: command-line-assistant
upstream_project_url: https://github.com/rhel-lightspeed/command-line-assistant


srpm_build_deps:
  - cargo
  - git
  - libzstd-devel

actions:
  # The last step here is required by Packit to return the archive name
  # https://packit.dev/docs/configuration/actions#create-archive
  create-archive:
    - bash -c "cargo install cargo-vendor-filterer"
    - bash -c "cargo xtask spec"
    - bash -c "cat target/command-line-assistant.spec"
    - bash -c "cp target/command-line-assistant* packaging/"
    - bash -c "ls -1 target/command-line-assistant*.tar.zstd | grep -v 'vendor'"
  # Do nothing with spec file. Two steps here are for debugging
  fix-spec-file:
    - bash -c "cat packaging/command-line-assistant.spec"
    - bash -c "ls -al packaging/"

jobs:
  # Build RPMs for each pull request
  - job: copr_build
    trigger: pull_request
    owner: "@rhel-lightspeed"
    project: command-line-assistant
    targets:
      - rhel-9-x86_64
      - rhel-9-aarch64
      - epel-9-ppc64le # there is no rhel9-ppc64le in copr
      - rhel-9-s390x
      - rhel-10-x86_64
      - rhel-10-aarch64
      - rhel-10-ppc64le
      - rhel-10-s390x
      - fedora-41-x86_64
      - fedora-41-aarch64
      - fedora-41-ppc64le
      - fedora-41-s390x
      - fedora-42-x86_64
      - fedora-42-aarch64
      - fedora-42-ppc64le
      - fedora-42-s390x
      - fedora-43-x86_64
      - fedora-43-aarch64
      - fedora-43-ppc64le
      - fedora-43-s390x
  # Build RPMs for main branch
  - job: copr_build
    trigger: commit
    branch: main
    owner: "@rhel-lightspeed"
    project: command-line-assistant
    targets:
      - rhel-9-x86_64
      - rhel-9-aarch64
      - epel-9-ppc64le # there is no rhel9-ppc64le in copr
      - rhel-9-s390x
      - rhel-10-x86_64
      - rhel-10-aarch64
      - rhel-10-ppc64le
      - rhel-10-s390x
      - fedora-41-x86_64
      - fedora-41-aarch64
      - fedora-41-ppc64le
      - fedora-41-s390x
      - fedora-42-x86_64
      - fedora-42-aarch64
      - fedora-42-ppc64le
      - fedora-42-s390x
      - fedora-43-x86_64
      - fedora-43-aarch64
      - fedora-43-ppc64le
      - fedora-43-s390x

  # Test jobs
  - job: tests
    identifier: level1-tests
    trigger: pull_request
    fmf_url: "https://gitlab.cee.redhat.com/rhel-lightspeed/enhanced-shell/cla-tests"
    fmf_ref: "develop"
    tmt_plan: "level1"
    use_internal_tf: True
    targets:
      epel-9-x86_64:
        distros: [RHEL-9.7.0-Nightly]
      epel-10-x86_64:
        distros: [RHEL-10.1-Nightly]
      epel-9-aarch64:
        distros: [RHEL-9.7.0-Nightly]
      epel-10-aarch64:
        distros: [RHEL-10.1-Nightly]
    tf_extra_params:
      environments:
        - settings:
            provisioning:
              tags:
                BusinessUnit: rhel_sst_lightspeed@upstream
    labels:
      - level1
      - default
