ci:
  skip:
    # rpm library is not available in the CI
    - rpmlint

minimum_pre_commit_version: "3.8.0"

repos:
  - repo: https://github.com/rpm-software-management/rpmlint
    rev: 2.7.0
    hooks:
      - id: rpmlint
        files: \.spec

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.12
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]

      # Show the diff of what would change.
      - id: ruff-format
        name: ruff-format-diff
        args: [--diff]

      # Run the formatter.
      - id: ruff-format

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v5.0.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "check-toml"
      - id: "check-yaml"
      - id: "check-merge-conflict"

  - repo: https://github.com/packit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: check-rebase
        args:
          - https://github.com/rhel-lightspeed/command-line-assistant.git
        stages: [manual, pre-push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
      additional_dependencies:
        - pytest
        - types-requests
        - dasbus
        - setuptools
        - responses
        - tomli
        - setuptools
        - sqlalchemy

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.0
    hooks:
      - id: gitleaks
        stages: [manual, pre-push]

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        exclude: ^(docs/conf.py|setup.py|tests/|scripts)
        args: ["-vv", "-c", "pyproject.toml", "command_line_assistant", "--fail-under", "100"]
        # Workaround mentioned at https://github.com/econchick/interrogate/issues/60#issuecomment-735436566
        pass_filenames: false

  - repo: local
    hooks:
      - id: check-for-missing-sphinx-docs
        name: check for missing sphinx docs
        entry: python scripts/check_sphinx_docs.py
        language: python
        pass_filenames: false
