version: 1

environment:
  secrets:
    WATSONX_APIKEY: |
      ea2a89aa-6a78-40e0-906e-140f623c45b0,gtA3ICu2hgS+vyV+yjWLr+R1/ELzzS2/KRPhyJ+vT
      Ic7et69TGy8415nAXxVA6IevjsbErsq6XLsFi9UUh8se5B6Y1YtYI1IPtFB9joCyC9O17Kd3pf5MXL
      td399xRYoDLFCew+N7MURXuQBorWjPlb01oSolj7kqcfXcwVwJ+vaBXIYbVofUZ/57F8J1MUC4qqqX
      rUSTL4dcNB0xbxVWqT5It1f0NV+obQB5Ajo+84LltqYIoYSmfTJtZhjAgIeiJEO79x9vKYMa6tzS00
      JotwUWk1lkiMoq0wLEowVCBpsuUOJLXCDprjIjQ5NcT/joR9ngMB8Odn0xRMsiUPK+3Sl2M6aMAKgo
      VfFlS5f7DxJc/Ug+W17pWmQdqfwVzD8LL+zPn3RqjNZnTat6VCgcCePKFzFi9KS4oLENJb2kalBS7n
      pU5IqgQAq631CfHHTIvsXe9xFOIY/1gCe9u3/7T4O8te+QffKkIO5xBJOpIIEy0RTO4y/F5HRDZ35Y
      fDvpdU+mKTWw4eJcZZ6P31osjsxzNEPliMULETY+ChdcU0uddKkVRlZiIjPgYBV8J8LNjaXdKPEEDi
      Oj21ZvsY1i3VGE7hW6r1M9Tbv4GwbVBpyaNg9zDxClXhZuoNhILhKZhGryFDWFm1Wxf/n6W9PNQk3h
      kLBhtjJNQTwXyJM1hU=