output_capture: # if '^' is used, last command output will be used for query context
  enforce_script: false  # otherwise recording via script session will be enforced
  output_file: /tmp/command-line-assistant_output.txt  # file with output(s) of regular commands (e.g. ls, echo, etc.)
  prompt_separator: '$'  # Keep non-empty if your file contains only output of commands (not prompt itself)
backend_service:
  query_endpoint: http://0.0.0.0:8080/v1/query/
history:
  enabled: true
  filepath: command-line-assistant_history.json
  max_size: 100  # max number of queries in history (including responses)
