version: "3"

services:
  postgres:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: cla
      POSTGRES_DB: history
    ports:
      - 5432:5432

  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: cla
      MARIADB_DATABASE: history
    ports:
      - 3306:3306
    expose:
      - 3306

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: cla
      MYSQL_DATABASE: history
    ports:
      - 3306:3306
    expose:
      - 3306

  # Inspect DB
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
