# Use CentOS Stream 10 as the base image
FROM quay.io/fedora/fedora:42@sha256:c877f0d32691746f56a6dc8fa73fd8d10606d2059acd535dff7924618e7cf995

# Install Python, pip, and development tools
RUN dnf install -y \
    python3-pip \
    'pkgconfig(cairo)' \
    'pkgconfig(cairo-gobject)' \
    'pkgconfig(gobject-introspection-1.0)' \
    'pkgconfig(mariadb)' \
    /usr/bin/pg_config && \
    dnf clean all

# Upgrade pip
RUN python -m pip install --upgrade pip

# Set up a working directory
WORKDIR /workspace
