FROM registry.access.redhat.com/ubi10/ubi:latest@sha256:eaa1ccdf1533e02d59eeed435cfb19cab37d4a4ae2d7a0801fa9f1f575654f62 AS base

ENV DNF_DEFAULT_OPTIONS "-y --nodocs --setopt=keepcache=0 --setopt=tsflags=nodocs --setopt=install_weak_deps=False"

# Build the python wheel
FROM base AS build

WORKDIR /project

COPY crates/ ./crates/
COPY Cargo.toml Cargo.lock .cargo .

# Install Python, pip, and development tools
RUN dnf install $DNF_DEFAULT_OPTIONS \
        gcc \
        g++ \
        cargo \
        openssl-devel \
    && dnf clean all

RUN cargo build --release \
    && cargo xtask manpages

FROM base AS final

# Add in data about the build. (These come from Konflux.)
ARG COMMIT_SHA=development
ARG COMMIT_TIMESTAMP=development
ARG VERSION=0.4.2
ARG SOURCE_DATE_EPOCH

# Config
COPY data/release/xdg/config.toml /etc/xdg/command-line-assistant/config.toml

RUN sed -i 's/^cert_file = .*/cert_file = "\/run\/secrets\/etc-pki-entitlement\/cert.pem"/' /etc/xdg/command-line-assistant/config.toml \
    && sed -i 's/^key_file = .*/key_file = "\/run\/secrets\/etc-pki-entitlement\/key.pem"/' /etc/xdg/command-line-assistant/config.toml

# # Systemd specifics
COPY data/release/systemd/clad.service /usr/lib/systemd/system/clad.service
COPY data/release/systemd/clad.tmpfiles.conf /usr/lib/tmpfiles.d/clad.tmpfiles.conf

# # Manpages
# COPY --from=build /project/target/man/c.1 /usr/share/man/man1/
# COPY data/release/man/clad.8 /usr/share/man/man/8

# # The wheel build
COPY --from=build /project/target/release/c /usr/bin/c
COPY --from=build /project/target/release/clad /usr/bin/clad

# This directory is checked by ecosystem-cert-preflight-checks task in Konflux
RUN mkdir /licenses
COPY LICENSE /licenses/

RUN useradd --system --create-home lightspeed
USER lightspeed

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]

# Labels for enterprise contract
LABEL com.redhat.component=rhel-lightspeed-command-line-assistant
LABEL description="Red Hat Enterprise Linux Lightspeed"
LABEL distribution-scope=private
LABEL io.k8s.description="Red Hat Enterprise Linux Lightspeed"
LABEL io.k8s.display-name="RHEL Lightspeed"
LABEL io.openshift.tags="rhel,lightspeed,ai,assistant,rag"
LABEL name=rhel-lightspeed-command-line-assistant
LABEL org.opencontainers.image.created=${SOURCE_DATE_EPOCH}
LABEL release="${VERSION}"
LABEL version=${VERSION}
LABEL url="https://github.com/rhel-lightspeed/command-line-assistant"
LABEL vendor="Red Hat, Inc."
LABEL summary="Red Hat Enterprise Linux Lightspeed"
