name: Require PR labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  require-type-label:
    if: ${{ !contains(fromJson('["dependabot", "pre-commit-ci", "renovate"]'), github.actor ) }}
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@8afbe8ae6ab7647d0c9f0cfa7c2f939650d22509 # v5
        with:
          mode: exactly
          count: 1
          labels: "kind/.*"
          use_regex: true
