name: Generate release-artifacts

on:
  push:
    tags:
        - '*'

permissions:
  contents: write

jobs:
  generate:
    name: Generate  builds
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@53af8e1e538a0ffab949cdde3e332d8e58e8630f # v2.1
        id: tagName
        with:
          tagRegex: "v(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.

      - name: Checkout the repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Install dependencies
        run: |
          # TODO(r0x0d): Refactor this https://issues.redhat.com/browse/RSPEED-339
          sudo apt update -y
          sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0 -y
          make install

      - name: Generate distribution tarball
        run: |
          make distribution-tarball SPHINXBUILD=$(pwd)/.venv/bin/sphinx-build
        env:
          VERSION: '${{ steps.tagName.outputs.tag }}'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@81c65b7cd4de9b2570615ce3aad67a41de5b1a13 # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
