name: Generate release-artifacts

on:
  push:
    tags:
        - '*'

permissions:
  contents: write

jobs:
  generate:
    name: Generate  builds
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@9a8716825750e73195b02db42777b92ffe960605 # v2.1.4
        id: tagName
        with:
          tagRegex: "v(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.

      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install dependencies
        run: |
          # TODO(r0x0d): Refactor this https://issues.redhat.com/browse/RSPEED-339
          sudo apt update -y
          sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0 -y
          make install

      - name: Generate distribution tarball
        run: |
          make distribution-tarball SPHINXBUILD=$(pwd)/.venv/bin/sphinx-build
        env:
          VERSION: '${{ steps.tagName.outputs.tag }}'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
