name: Sanity

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    name: Sanity - ${{ matrix.python-version }}
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - '3.9'
          - '3.12'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          version: 2.20.1
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install dependencies
        run: |
          pdm install -v
          pdm info
          echo "$(pdm venv --path in-project)/bin" >> $GITHUB_PATH

      - name: Run pyright
        uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.389
          python-version: ${{ matrix.python-version }}
          annotate: errors
