name: Sanity

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    name: Sanity - ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ['3.9', '3.12']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          # TODO(r0x0d): Refactor this https://issues.redhat.com/browse/RSPEED-339
          sudo apt update -y
          sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0 -y
          make install
          echo "$(poetry env info -p)/bin" >> $GITHUB_PATH

      - name: Run pyright
        uses: jakebailey/pyright-action@v2
        with:
          python-version: ${{ matrix.python-version }}
          annotate: errors
