name: Sanity

on:
  - push
  - pull_request

jobs:
  sanity:
    runs-on: ubuntu-latest
    name: Sanity - ${{ matrix.python-version }}
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - '3.9'
          - '3.12'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run pyright
        uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.389
          python-version: ${{ matrix.python-version }}

