name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream${{ matrix.centos-version }}
    strategy:
      matrix:
        include:
          - centos-version: '9'
            python-version: '3.9'
          - centos-version: '10'
            python-version: '3.12'

    steps:
      - name: Install Act dependencies
        if: ${{ env.ACT }}
        run: dnf install -y nodejs

      - name: Set up newer Node.js version
        if: ${{ env.ACT }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Enable CRB repository
        run: dnf config-manager --set-enabled crb

      - name: Install package dependencies
        run: dnf install -y make git gcc gpg pkgconfig gobject-introspection-devel cairo-devel cairo-gobject-devel glib2-devel

      - run: uv python install ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: uv sync --extra dev --extra docs

      - name: Run unit tests
        run: |
          make unit-test-coverage
          make coverage

      - name: Upload coverage reports to Codecov
        if: ${{ !env.ACT }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          verbose: true

      # https://docs.codecov.com/docs/test-analytics
      - name: Upload test results to Codecov
        if: ${{ !cancelled() && !env.ACT }}
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1.2.1
