name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust-toolchain: '1.84.1'

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-toolchain }}

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose --all-features
        env:
          # https://doc.rust-lang.org/cargo/reference/config.html#buildincremental
          CARGO_INCREMENTAL: '0'
          RUST_BACKTRACE: '1'

      - uses: cargo-bins/cargo-binstall@main

      # Used for generating test coverage
      - name: Generate test coverage
        run: |
          cargo binstall cargo-tarpaulin
          cargo tarpaulin --out Xml --output-dir coverage


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5
        with:
          files: ./coverage/cobertura.xml
          env_vars: OS,RUST
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # https://docs.codecov.com/docs/test-analytics
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
