name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream${{ matrix.centos-version }}
    strategy:
      matrix:
        include:
          - centos-version: '9'
            python-version: '3.9'
          - centos-version: '10'
            python-version: '3.12'

    steps:
      - name: Install Act dependencies
        if: ${{ env.ACT }}
        run: dnf install -y nodejs

      - name: Set up newer Node.js version
        if: ${{ env.ACT }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22'

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Enable CRB repository
        run: dnf config-manager --set-enabled crb

      - name: Install package dependencies
        run: dnf install -y make git gcc gpg pkgconfig gobject-introspection-devel cairo-devel cairo-gobject-devel glib2-devel

      - run: uv python install ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: uv sync --extra dev --extra docs

      - name: Run unit tests
        run: |
          make unit-test-coverage
          make coverage

      - name: Upload coverage reports to Codecov
        if: ${{ !env.ACT }}
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # https://docs.codecov.com/docs/test-analytics
      - name: Upload test results to Codecov
        if: ${{ !cancelled() && !env.ACT }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
