name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.12']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          # TODO(r0x0d): Refactor this https://issues.redhat.com/browse/RSPEED-339
          sudo apt update -y
          sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0 -y
          make install
          echo "$(poetry env info -p)/bin" >> $GITHUB_PATH

      - name: Run unit tests
        run: make unit-test-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # https://docs.codecov.com/docs/test-analytics
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
